- hosts: testservers
  vars:
    ImageName: "subratit/projects-16th-nov"
    Namespace: "local-namespace-dfly"
    imageTag: "latest02"
  #remote_user: ansible
  become: true
  become_user: root
  gather_facts: no
  connection: local
  tasks:
    - name: Create Namespace {{ Namespace }}
      command: "/usr/bin/kubectl --version"
      ignore_errors: yes
