apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: simple-web-container
        image: subratit/projects-jan-5:latest
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: simple-web-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    targetPort: 80
    nodePort: 31003
  type: NodePort
  selector:
    app: simple-web
